#!/usr/bin/env node
// pack-web.js
// Reads all files from web/, gzips each, and generates firmware/web_files.h
// with PROGMEM byte arrays and a directory table for the HTTP server.

import { readdirSync, readFileSync, writeFileSync, statSync, existsSync, mkdirSync } from 'fs';
import { join, relative, extname } from 'path';
import { gzipSync } from 'zlib';

const webDir = '../out/dist';
const outFile = '../out/web_files.h';


const CONTENT_TYPES = {
    '.html': 'text/html',
    '.css':  'text/css',
    '.js':   'application/javascript',
    '.json': 'application/json',
    '.png':  'image/png',
    '.jpg':  'image/jpeg',
    '.jpeg': 'image/jpeg',
    '.svg':  'image/svg+xml',
    '.ico':  'image/x-icon',
    '.woff': 'font/woff',
    '.woff2':'font/woff2',
    '.ttf':  'font/ttf',
    '.txt':  'text/plain',
};

function contentType(filename) {
    return CONTENT_TYPES[extname(filename).toLowerCase()] ?? 'application/octet-stream';
}

function cIdentifier(urlPath) {
    // "/foo/bar.html" -> "foo_bar_html"
    return urlPath.replace(/^\//, '').replace(/[^a-zA-Z0-9]/g, '_') || 'root';
}

function collectFiles(dir, base = dir, out = []) {
    for (const entry of readdirSync(dir)) {
        const full = join(dir, entry);
        if (statSync(full).isDirectory()) {
            collectFiles(full, base, out);
        } else {
            out.push(full);
        }
    }
    return out;
}

function formatHex(buf) {
    const rows = [];
    for (let i = 0; i < buf.length; i += 16) {
        const slice = buf.subarray(i, i + 16);
        rows.push('    ' + Array.from(slice, b => `0x${b.toString(16).padStart(2, '0')}`).join(', '));
    }
    return rows.join(',\n');
}

// ---- main ----


if (!existsSync(webDir)) {
    console.error(`Directory '${webDir}' not found`);
    process.exit(1);
}

const files = collectFiles(webDir);
if (files.length === 0) {
    console.error(`No files found in '${webDir}'`);
    process.exit(1);
}

// Skip regeneration if output is newer than all input files
if (existsSync(outFile)) {
    const outMtime = statSync(outFile).mtimeMs;
    const anyNewer = files.some(f => statSync(f).mtimeMs > outMtime);
    if (!anyNewer) {
        console.log(`${outFile} is up to date`);
        process.exit(0);
    }
}

const out = [
    '// Auto-generated by pack-web.js — do not edit',
    '',
    '#pragma once',
    '#include <stddef.h>',
    '#include <stdint.h>',
    '#include <pgmspace.h>',
    '',
    'struct WEB_FILE {',
    '    const char*    path;',
    '    const char*    content_type;',
    '    const uint8_t* data;',
    '    size_t         size;',
    '};',
    '',
];

const entries = [];
let totalSize = 0;

for (const file of files) {
    const urlPath = '/' + relative(webDir, file).replace(/\\/g, '/');
    const id      = cIdentifier(urlPath);
    const raw     = readFileSync(file);
    const gz      = gzipSync(raw, { level: 9 });

    out.push(`// ${urlPath}  (${raw.length} B → ${gz.length} B gzipped)`);
    out.push(`static const uint8_t _wf_${id}[] PROGMEM = {`);
    out.push(formatHex(gz));
    out.push('};');
    out.push('');

    entries.push({ urlPath, id, type: contentType(file), size: gz.length });
    console.log(`  ${urlPath}: ${raw.length} B → ${gz.length} B`);
    totalSize += gz.length;
}

console.log("Total gzipped size: " + totalSize + " B");

out.push('static const WEB_FILE web_files[] = {');
for (const { urlPath, id, type } of entries) {
    out.push(`    { "${urlPath}", "${type}", _wf_${id}, sizeof(_wf_${id}) },`);
}
out.push('};');
out.push('');
out.push(`static const int web_files_count = ${entries.length};`);
out.push('');

writeFileSync(outFile, out.join('\n'));
console.log(`\nWrote ${outFile} with ${entries.length} file(s)`);
